// <auto-generated />
namespace Lotto.Model.Migrations.Hub
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLotterySourceConfigs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLotterySourceConfigs));
        
        string IMigrationMetadata.Id
        {
            get { return "201604071318539_AddLotterySourceConfigs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
