// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Lotto.Model.Migrations.Process
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameSchemaChangeLotteryDrawings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameSchemaChangeLotteryDrawings));
        
        string IMigrationMetadata.Id
        {
            get { return "201505141331526_RenameSchemaChangeLotteryDrawings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
